const releases={
 lionheart:{title:'LIONHEART',year:'2016',cover:'lionheart.jpg',spotify:'https://open.spotify.com/album/6dvu4emuyuaYtqEnydQNql?si=lpANmSlUSA6TPjpsyVQjwA&utm_source=copy-link',art:'Niklas Sundin',lineup:['W. Bergbacka - Vocals','F. Rasmusson - Guitar','A. Jagfeldt - Guitar','A. Dahlström - Drums','Askebloss - Bass'],tracks:['TAKE YOUR FEAR','DOWN THROUGH THE GARDENS','THE MIRROR OF TRAGEDY','TRUTH UNFOLDS','LIONHEART','THE ICE STORM (instrumental)','THE LIGHT WILL RAPE US ALL','MY JOURNEY ENDS WITHIN','INSANITY UNLEASHED','ALL IT TAKES','PUNISHMENT OF LIFE','SUICIDAL FINAL ART','THE PASSAGE (instrumental)']},
 terminal:{title:'TERMINAL',year:'2018',cover:'terminal.jpg',spotify:'https://open.spotify.com/album/1tWYulX6rO3cxWLejG9N49?si=0gMgp1l0SPmZejF-PzI4pg&utm_source=copy-link',art:'Emil Hermansson',lineup:['A. Jagfeldt - Guitar','W. Bergbacka - Vocals','F. Rasmusson - Guitar','J. Gunneröd - Bass','A. Dahlström - Drums'],tracks:['TERMINAL','IN DEATH WE TRUST','LIBERATION','INTO THE VOID','HARDSHIPS (feat. Tomas Lindberg)','THE GATEWAY (instrumental)','RUINS','NOTHING REMAINS','DETHRONED','BENEATH THE BLEEDING SKY','MY HAVEN BURNS','THE END IS MINE','REMEMBER ME','STRIKE FROM THE ASHES (All It Takes - Part 2)']},
 inferno:{title:'INFERNO',year:'2023',cover:'inferno.jpg',spotify:'https://open.spotify.com/album/6rkvCMbB2eOusM8Usl74XD?si=x1zPsxEcSliHYvTsoxzG6w&utm_source=copy-link',art:'Emil Hermansson',lineup:null,tracks:['AS GRIEF NEEDS ETERNITY STILL (instrumental)','ALL THAT AVAILS IS FLIGHT','INFERNO','DELIVERED IN BLOOD','ABOVE THE SERPENTS WORLD','AGONIZING ENDLESS BURDEN','THE PORTAL (instrumental)','FOR ONE LAST TIME','NOT EVEN YOU','SUICIDAL FINAL MOMENT']}
};

const TRACK_CREDITS={
 lionheart:[['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka','Leon Farester - Violin','Petter Pettersson - Cello','Fanny LaBrosse - choir','Larza Skjuttorp - choir'],['Music & lyrics: W. Bergbacka','Guest: Fanny LaBrosse (vocals)'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: F. Rasmusson']],
 terminal:[['Music: F. Rasmusson, A. Jagfeldt, A. Dahlström','Lyrics: W. Bergbacka'],['Music: F. Rasmusson, A. Jagfeldt, A. Dahlström','Lyrics: W. Bergbacka'],['Music: A. Jagfeldt','Lyrics: W. Bergbacka'],['Music: A. Jagfeldt','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka','Guest vocals: Tomas Lindberg'],['Music: A. Jagfeldt','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: A. Jagfeldt','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: A. Jagfeldt, A. Dahlström, F. Rasmusson','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: A. Jagfeldt','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: A. Dahlström, W. Bergbacka, A. Jagfeldt','Lyrics: W. Bergbacka']],
 inferno:[['Music: Joakim Hedestedt','Based on an idea by: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: F. Rasmusson, R. Lagerborg','Lyrics: W. Bergbacka'],['Music: F. Rasmusson, S. Myrén','Lyrics: W. Bergbacka'],['Music: F. Rasmusson'],['Music: F. Rasmusson','Lyrics: W. Bergbacka'],['Music: F. Rasmusson, S. Myrén','Lyrics: W. Bergbacka'],['Music: F. Rasmusson','Lyrics: W. Bergbacka']]
};

function footer(){return `<footer class="footer"><div class="social"><a target="_blank" rel="noopener" href="https://open.spotify.com/artist/4aeOOA7Dt2vpV5xvnwOJbW?si=OusMkbsZS2uwnRHXbycyMQ&utm_source=copy-link">Spotify</a><a target="_blank" rel="noopener" href="https://darknessgbg.bandcamp.com/music">Bandcamp</a><a target="_blank" rel="noopener" href="https://www.facebook.com/share/187VC6S991/?mibextid=wwXIfr">Facebook</a></div><div class="tag">#darknessgbg</div></footer>`}
function head(active=''){return `<header class="site-head"><div class="brand">PREVAIL IN DARKNESS</div><nav class="nav">${['HOME','LIONHEART','TERMINAL','INFERNO','SINGLES'].map(x=>`<a class="${active===x?'active':''}" href="${x==='HOME'?'index':x.toLowerCase()}.html">${x}</a>`).join('')}</nav></header>`}
function renderAlbum(id){const r=releases[id];document.title=`${r.title} — Prevail In Darkness`;document.body.innerHTML=head(r.title)+`<main><section class="release-head"><img class="cover" src="assets/${r.cover}" alt="${r.title} cover"><div><div class="kicker">ALBUM</div><h1>${r.title}</h1><div class="meta">RELEASED: ${r.year}</div><p style="margin:25px 0"><a class="btn" target="_blank" rel="noopener" href="${r.spotify}">LISTEN ON SPOTIFY ↗</a></p><ol class="tracks">${r.tracks.map((t,i)=>`<li><a href="lyrics.html?release=${id}&track=${i}"><span class="num">${i+1}.</span><span>${t}</span></a></li>`).join('')}</ol><div class="credits">${r.lineup?`<strong>LINE-UP</strong><br>${r.lineup.join('<br>')}<br><br>`:''}<strong>Artwork by:</strong> ${r.art}</div></div></section></main>`+footer()}
